# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-07 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, 'HTML'), (4, '最近评论'), (3, '最热文章'), (2, '最新文章')], default=1, verbose_name='展示类型'),
        ),
    ]
