# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-14 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20191107_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(3, '最热文章'), (1, 'HTML'), (4, '最近评论'), (2, '最新文章')], default=1, verbose_name='展示类型'),
        ),
    ]
